Introduce MP_EXT validation capabilities
tarantool/msgpuck pull request #19
Opened 2022-03-18 11:25 UTC by sergepetrenko

Currently mp_check() checks that the given buffer is a valid msgpack
string, however it simply skips MP_EXT fields, since it knows nothing
of their contents.

Let's introduce a stub for checking MP_EXT contents.
The stub will be replaced with an application-defined callback checking
the ext types it has introduced.

Needed for tarantool/tarantool#6857

2022-03-21 11:26 UTC, locker requested changes

2022-03-21 11:26 UTC, locker commented on msgpuck.h
> +typedef int (*mp_check_ext_f)(const char *data, int8_t type, uint32_t len);
Nit: I think we should name this function `mp_check_ext_data_f`, because it checks extension data without a header. Also, I think that the type should go first in the argument list, because it determines how the data is going to be interpreted:

```
typedef int (*mp_check_ext_data_f)(int8_t type, const char *data, uint32_t len);
```

2022-03-21 11:26 UTC, locker commented on msgpuck.h
> +typedef int (*mp_check_ext_f)(const char *data, int8_t type, uint32_t len);
Please add a test.

2022-05-12 09:31 UTC, sergepetrenko commented
@locker, thanks for the review and sorry for such a late reply.

I've adressed your comments, please see the updated patch.

Here are all the changes:

<details>
<summary>diff</summary>

```diff
diff --git a/msgpuck.c b/msgpuck.c
index 2ed8ab4..f3ef7a5 100644
--- a/msgpuck.c
+++ b/msgpuck.c
@@ -60,7 +60,7 @@ mp_fprint_ext_f mp_fprint_ext = mp_fprint_ext_default;
 mp_snprint_ext_f mp_snprint_ext = mp_snprint_ext_default;
 
 int
-mp_check_ext_default(const char *data, int8_t type, uint32_t len)
+mp_check_ext_data_default(int8_t type, const char *data, uint32_t len)
 {
 	(void)data;
 	(void)type;
@@ -68,7 +68,7 @@ mp_check_ext_default(const char *data, int8_t type, uint32_t len)
 	return 0;
 }
 
-mp_check_ext_f mp_check_ext = mp_check_ext_default;
+mp_check_ext_data_f mp_check_ext_data = mp_check_ext_data_default;
 
 size_t
 mp_vformat(char *data, size_t data_size, const char *format, va_list vl)
diff --git a/msgpuck.h b/msgpuck.h
index 02ef31c..c9064a2 100644
--- a/msgpuck.h
+++ b/msgpuck.h
@@ -1081,12 +1081,12 @@ extern mp_snprint_ext_f mp_snprint_ext;
 int
 mp_snprint_ext_default(char *buf, int size, const char **data, int depth);
 
-typedef int (*mp_check_ext_f)(const char *data, int8_t type, uint32_t len);
+typedef int (*mp_check_ext_data_f)(int8_t type, const char *data, uint32_t len);
 
 /**
  * \brief Function called by mp_check() to validate user-defined MP_EXT types.
  */
-extern mp_check_ext_f mp_check_ext;
+extern mp_check_ext_data_f mp_check_ext_data;
 
 /**
  * \brief Default MP_EXT checker. Does nothing since knows nothing of
@@ -1094,7 +1094,7 @@ extern mp_check_ext_f mp_check_ext;
  * \retval 0
  */
 int
-mp_check_ext_default(const char *data, int8_t type, uint32_t len);
+mp_check_ext_data_default(int8_t type, const char *data, uint32_t len);
 
 /**
  * \brief Check that \a cur buffer has enough bytes to decode a string header
@@ -2555,10 +2555,14 @@ mp_check(const char **data, const char *end)
 		if (mp_likely(l >= 0)) {
 			MP_CHECK_LEN(l);
 			if (mp_unlikely(c >= 0xd4 && c <= 0xd8)) {
-				/* Check MP_EXT contents. */
-				len = 1u << (c - 0xd4);
+				/*
+				 * Check MP_EXT contents. Everything but the
+				 * first byte (which stands for ext type) is the
+				 * payload.
+				 */
+				len = l - 1;
 				type = mp_load_u8(data);
-				if (mp_check_ext(*data, type, len) != 0)
+				if (mp_check_ext_data(type, *data, len) != 0)
 					return 1;
 				*data += len;
 			} else {
@@ -2618,7 +2622,7 @@ mp_check(const char **data, const char *end)
 			len = mp_load_u8(data);
 			type = mp_load_u8(data);
 			MP_CHECK_LEN(len);
-			if (mp_check_ext(*data, type, len) != 0)
+			if (mp_check_ext_data(type, *data, len) != 0)
 				return 1;
 			*data += len;
 			break;
@@ -2628,7 +2632,7 @@ mp_check(const char **data, const char *end)
 			len = mp_load_u16(data);
 			type = mp_load_u8(data);
 			MP_CHECK_LEN(len);
-			if (mp_check_ext(*data, type, len) != 0)
+			if (mp_check_ext_data(type, *data, len) != 0)
 				return 1;
 			*data += len;
 			break;
@@ -2638,7 +2642,7 @@ mp_check(const char **data, const char *end)
 			len = mp_load_u32(data);
 			type = mp_load_u8(data);
 			MP_CHECK_LEN(len);
-			if (mp_check_ext(*data, type, len) != 0)
+			if (mp_check_ext_data(type, *data, len) != 0)
 				return 1;
 			*data += len;
 			break;
diff --git a/test/msgpuck.c b/test/msgpuck.c
index ca65727..1ebbb46 100644
--- a/test/msgpuck.c
+++ b/test/msgpuck.c
@@ -1196,6 +1196,89 @@ test_mp_check()
 	return check_plan();
 }
 
+/**
+ * Check validity of a simple extension type.
+ * Its type is 0x42 and payload is a byte string where i-th byte value is its
+ * position from the end of the string.
+ */
+int
+mp_check_ext_data_test(int8_t type, const char *data, uint32_t len)
+{
+	if (type != 0x42)
+		return 1;
+	for (uint32_t i = 0; i < len; i++) {
+		if ((unsigned char)data[i] != len - i)
+			return 1;
+	}
+	return 0;
+}
+
+int
+test_mp_check_ext_data()
+{
+	plan(24);
+	header();
+
+#define valid(data, fmt, ...) ({ \
+	const char *p = data; \
+	is(mp_check(&p, p + sizeof(data) - 1), 0, fmt, ## __VA_ARGS__); \
+});
+
+	mp_check_ext_data_f mp_check_ext_data_svp = mp_check_ext_data;
+	mp_check_ext_data = mp_check_ext_data_test;
+
+	/* ext8 */
+	invalid("\xc7\x00\x13", "invalid ext8 - bad type");
+	invalid("\xc7\x01\x42\x13", "invalid ext8 - bad data");
+	valid("\xc7\x01\x42\x01", "valid ext8");
+
+	/* ext16 */
+	invalid("\xc8\x00\x00\x13", "invalid ext16 - bad type");
+	invalid("\xc8\x00\x01\x42\x13", "invalid ext16 - bad data");
+	valid("\xc8\x00\x01\x42\x01", "valid ext16");
+
+	/* ext32 */
+	invalid("\xc9\x00\x00\x00\x00\x13", "invalid ext32 - bad type");
+	invalid("\xc9\x00\x00\x00\x01\x42\x13", "invalid ext32 - bad data");
+	valid("\xc9\x00\x00\x00\x01\x42\x01", "valid ext32");
+
+	/* fixext8 */
+	invalid("\xd4\x13\x01", "invalid fixext8 - bad type")
+	invalid("\xd4\x42\x13", "invalid fixext8 - bad data")
+	valid("\xd4\x42\x01", "valid fixext8")
+
+	/* fixext16 */
+	invalid("\xd5\x13\x02\x01", "invalid fixext16 - bad type")
+	invalid("\xd5\x42\x13\x13", "invalid fixext16 - bad data")
+	valid("\xd5\x42\x02\x01", "valid fixext16")
+
+	/* fixext32 */
+	invalid("\xd6\x13\x04\x03\x02\x01", "invalid fixext32 - bad type")
+	invalid("\xd6\x42\x13\x13\x13\x13", "invalid fixext32 - bad data")
+	valid("\xd6\x42\x04\x03\x02\x01", "valid fixext32")
+
+	/* fixext64 */
+	invalid("\xd7\x13\x08\x07\x06\x05\x04\x03\x02\x01",
+		"invalid fixext64 - bad type")
+	invalid("\xd7\x42\x13\x13\x13\x13\x13\x13\x13\x13",
+		"invalid fixext64 - bad data")
+	valid("\xd7\x42\x08\x07\x06\x05\x04\x03\x02\x01",
+	      "valid fixext64")
+
+	/* fixext128 */
+	invalid("\xd8\x13\x10\x0f\x0e\x0d\x0c\x0b\x0a\x09\x08\x07\x06\x05\x04"
+		"\x03\x02\x01", "invalid fixext128 - bad type")
+	invalid("\xd8\x42\x13\x13\x13\x13\x13\x13\x13\x13\x13\x13\x13\x13\x13"
+		"\x13\x13\x13", "invalid fixext128 - bad data")
+	valid("\xd8\x42\x10\x0f\x0e\x0d\x0c\x0b\x0a\x09\x08\x07\x06\x05\x04"
+	      "\x03\x02\x01", "valid fixext128")
+
+	mp_check_ext_data = mp_check_ext_data_svp;
+
+	footer();
+	return check_plan();
+}
+
 #define int_eq(a, b) (((a) - (b)) == 0)
 #define double_eq(a, b) (fabs((a) - (b)) < 1e-15)
 
@@ -1316,7 +1399,7 @@ test_overflow()
 
 int main()
 {
-	plan(23);
+	plan(24);
 	test_uints();
 	test_ints();
 	test_bools();
@@ -1338,6 +1421,7 @@ int main()
 	test_mp_print();
 	test_mp_print_ext();
 	test_mp_check();
+	test_mp_check_ext_data();
 	test_numbers();
 	test_overflow();
 

```

</details>

2022-05-12 09:32 UTC, sergepetrenko commented on msgpuck.h
> +typedef int (*mp_check_ext_f)(const char *data, int8_t type, uint32_t len);
Good point, fixed.

2022-05-12 09:32 UTC, sergepetrenko commented on msgpuck.h
> +typedef int (*mp_check_ext_f)(const char *data, int8_t type, uint32_t len);
Done.

2022-05-12 10:47 UTC, locker approved these changes

2022-05-12 10:47 UTC, merged