Introduce toggle for escaping '/'
tarantool/msgpuck pull request #21
Opened 2022-05-04 14:57 UTC by Lord-KA

It was decided that lua_cjson should have tarantool.compat (tarantool/tarantool#7000)
option that allows to toggle escaping '/'. For consistency msgpuck is to
switch the behavior too.

This patch provides function that sets '/' to be escaped or not.

Needed for tarantool/tarantool#6200

2022-05-06 14:15 UTC, ligurio requested changes

2022-05-06 14:15 UTC, ligurio commented on msgpuck.h
> +/** gh-6200 fix using gh-7000 */
Comment looks useless. We usually describe affected issues in commit message.

2022-05-12 09:15 UTC, Lord-KA commented on msgpuck.h
> +/** gh-6200 fix using gh-7000 */
Fixed

2022-06-07 22:54 UTC, Totktonada commented on hints.c
> +	NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
That's interesting. Here we introduce an incompatible change in msgpuck. It seems, we shouldn't.

2022-06-07 23:17 UTC, Totktonada commented on msgpuck.c
> +}
To be honest, I would just change the `mp_char2escape` array from the external code. It is more like internal specific API and not necessarily requires incapsulation using an accessor function. At the same time it is the minimal and most flexible option: we'll able change the table as we wish without further changes on the library side.

@igormunkin, I would like to know your opinion here too.

It seems, we don't ever need to drop `const` here, because it is about pointers we store, not about ability to change array elements.

<details>
<summary>Regarding the accessor (just in case)</summary>

Why not `mp_char2escape['/'] = "\\/"` on the positive branch?

Why 'toogle' -- it sets the value? Why `msgpuck_*`, while all other functions are `mp_*`? I would write the accessor like so:

```c
/**
 * Returns the previous value.
 */
const char *
mp_set_forward_spash_escaping(bool is_enabled)
{
        const char *prev = mp_char2escape['/'];
        <...>
        return prev;
}
```

Or even:

```c
/**
 * Returns the previous value.
 */
const char *
mp_set_forward_spash_escaping(char what, bool is_enabled)
{
        unsigned char idx = (unsigned char)what;
        assert(idx < lengthof(mp_char2escape))
        const char *prev = mp_char2escape[idx];
        <...>
        return prev;
}
```

However I would prefer to don't provide an accessor.
</details>

2022-06-15 13:16 UTC, Lord-KA commented
It was decided to change toggler for msgpuck to Lua C function.

2022-06-22 12:44 UTC, closed without merging